# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenMarket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenMarket
  pod "BSImagePicker", "~> 3.1"

  pod 'SkeletonView'

  target 'OpenMarketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenMarketUITests' do
    # Pods for testing
  end

end
